# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Entity
version:      0.02
license: perl
version_from: lib/SQL/Entity.pm
installdirs:  site
requires:
    Abstract::Meta::Class:                    0
    Storable:                                 0

distribution_type: module
tests: t/*.t t/*/*.t
generated_by: ExtUtils::MakeMaker version 6.30
